language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install qtbase5-dev qtbase5-dev-tools xdg-utils

script:
  - qmake -qt5 CONFIG+=release PREFIX=/usr
  - make -j$(nproc)
  - make INSTALL_ROOT=../appdir -j$(nproc) install
  - wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt-continuous-x86_64.AppImage
  - export VERSION=$(git rev-parse --short HEAD) # linuxdeployqt uses this for naming the file
  - LD_LIBRARY_PATH="appdir/usr/lib/pibreeze/" ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/pibreeze.desktop -bundle-non-qt-libs
  - LD_LIBRARY_PATH="appdir/usr/lib/pibreeze/" ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/pibreeze.desktop -appimage

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
